export type Language = { code: string; name: string; native: string; rtl?: boolean };

export const RTL_CODES = ["ar", "he", "fa", "ur", "ps", "sd", "ug", "yi", "ku", "dv"];

export const LANGUAGES: Language[] = [
  { code: "en", name: "English", native: "English" },
  { code: "zh", name: "Chinese (Simplified)", native: "简体中文" },
  { code: "zh-TW", name: "Chinese (Traditional)", native: "繁體中文" },
  { code: "hi", name: "Hindi", native: "हिन्दी" },
  { code: "es", name: "Spanish", native: "Español" },
  { code: "fr", name: "French", native: "Français" },
  { code: "ar", name: "Arabic", native: "العربية", rtl: true },
  { code: "bn", name: "Bengali", native: "বাংলা" },
  { code: "pt", name: "Portuguese", native: "Português" },
  { code: "ru", name: "Russian", native: "Русский" },
  { code: "ur", name: "Urdu", native: "اردو", rtl: true },
  { code: "id", name: "Indonesian", native: "Bahasa Indonesia" },
  { code: "de", name: "German", native: "Deutsch" },
  { code: "ja", name: "Japanese", native: "日本語" },
  { code: "sw", name: "Swahili", native: "Kiswahili" },
  { code: "mr", name: "Marathi", native: "मराठी" },
  { code: "te", name: "Telugu", native: "తెలుగు" },
  { code: "tr", name: "Turkish", native: "Türkçe" },
  { code: "ta", name: "Tamil", native: "தமிழ்" },
  { code: "vi", name: "Vietnamese", native: "Tiếng Việt" },
  { code: "ko", name: "Korean", native: "한국어" },
  { code: "it", name: "Italian", native: "Italiano" },
  { code: "fa", name: "Persian", native: "فارسی", rtl: true },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી" },
  { code: "pl", name: "Polish", native: "Polski" },
  { code: "uk", name: "Ukrainian", native: "Українська" },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", native: "മലയാളം" },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ" },
  { code: "ro", name: "Romanian", native: "Română" },
  { code: "nl", name: "Dutch", native: "Nederlands" },
  { code: "th", name: "Thai", native: "ไทย" },
  { code: "or", name: "Odia", native: "ଓଡ଼ିଆ" },
  { code: "ha", name: "Hausa", native: "Hausa" },
  { code: "my", name: "Burmese", native: "မြန်မာ" },
  { code: "am", name: "Amharic", native: "አማርኛ" },
  { code: "yo", name: "Yoruba", native: "Yorùbá" },
  { code: "ig", name: "Igbo", native: "Igbo" },
  { code: "uz", name: "Uzbek", native: "Oʻzbekcha" },
  { code: "ms", name: "Malay", native: "Bahasa Melayu" },
  { code: "tl", name: "Filipino", native: "Filipino" },
  { code: "ne", name: "Nepali", native: "नेपाली" },
  { code: "si", name: "Sinhala", native: "සිංහල" },
  { code: "km", name: "Khmer", native: "ភាសាខ្មែរ" },
  { code: "lo", name: "Lao", native: "ລາວ" },
  { code: "el", name: "Greek", native: "Ελληνικά" },
  { code: "hu", name: "Hungarian", native: "Magyar" },
  { code: "cs", name: "Czech", native: "Čeština" },
  { code: "sk", name: "Slovak", native: "Slovenčina" },
  { code: "sv", name: "Swedish", native: "Svenska" },
  { code: "da", name: "Danish", native: "Dansk" },
  { code: "fi", name: "Finnish", native: "Suomi" },
  { code: "no", name: "Norwegian", native: "Norsk" },
  { code: "is", name: "Icelandic", native: "Íslenska" },
  { code: "he", name: "Hebrew", native: "עברית", rtl: true },
  { code: "bg", name: "Bulgarian", native: "Български" },
  { code: "sr", name: "Serbian", native: "Српски" },
  { code: "hr", name: "Croatian", native: "Hrvatski" },
  { code: "bs", name: "Bosnian", native: "Bosanski" },
  { code: "sl", name: "Slovenian", native: "Slovenščina" },
  { code: "mk", name: "Macedonian", native: "Македонски" },
  { code: "sq", name: "Albanian", native: "Shqip" },
  { code: "lt", name: "Lithuanian", native: "Lietuvių" },
  { code: "lv", name: "Latvian", native: "Latviešu" },
  { code: "et", name: "Estonian", native: "Eesti" },
  { code: "ka", name: "Georgian", native: "ქართული" },
  { code: "hy", name: "Armenian", native: "Հայերեն" },
  { code: "az", name: "Azerbaijani", native: "Azərbaycanca" },
  { code: "kk", name: "Kazakh", native: "Қазақша" },
  { code: "ky", name: "Kyrgyz", native: "Кыргызча" },
  { code: "tg", name: "Tajik", native: "Тоҷикӣ" },
  { code: "tk", name: "Turkmen", native: "Türkmençe" },
  { code: "mn", name: "Mongolian", native: "Монгол" },
  { code: "ps", name: "Pashto", native: "پښتو", rtl: true },
  { code: "ku", name: "Kurdish", native: "کوردی", rtl: true },
  { code: "sd", name: "Sindhi", native: "سنڌي", rtl: true },
  { code: "as", name: "Assamese", native: "অসমীয়া" },
  { code: "mai", name: "Maithili", native: "मैथिली" },
  { code: "sa", name: "Sanskrit", native: "संस्कृतम्" },
  { code: "bho", name: "Bhojpuri", native: "भोजपुरी" },
  { code: "zu", name: "Zulu", native: "isiZulu" },
  { code: "xh", name: "Xhosa", native: "isiXhosa" },
  { code: "af", name: "Afrikaans", native: "Afrikaans" },
  { code: "st", name: "Sesotho", native: "Sesotho" },
  { code: "sn", name: "Shona", native: "chiShona" },
  { code: "ny", name: "Chichewa", native: "Chichewa" },
  { code: "so", name: "Somali", native: "Soomaali" },
  { code: "rw", name: "Kinyarwanda", native: "Kinyarwanda" },
  { code: "ti", name: "Tigrinya", native: "ትግርኛ" },
  { code: "om", name: "Oromo", native: "Afaan Oromoo" },
  { code: "ff", name: "Fulah", native: "Fulfulde" },
  { code: "wo", name: "Wolof", native: "Wolof" },
  { code: "mg", name: "Malagasy", native: "Malagasy" },
  { code: "ca", name: "Catalan", native: "Català" },
  { code: "gl", name: "Galician", native: "Galego" },
  { code: "eu", name: "Basque", native: "Euskara" },
  { code: "cy", name: "Welsh", native: "Cymraeg" },
  { code: "ga", name: "Irish", native: "Gaeilge" },
  { code: "mt", name: "Maltese", native: "Malti" },
  { code: "lb", name: "Luxembourgish", native: "Lëtzebuergesch" },
  { code: "be", name: "Belarusian", native: "Беларуская" },
  { code: "jv", name: "Javanese", native: "Basa Jawa" },
  { code: "su", name: "Sundanese", native: "Basa Sunda" },
  { code: "ceb", name: "Cebuano", native: "Cebuano" },
  { code: "haw", name: "Hawaiian", native: "ʻŌlelo Hawaiʻi" },
  { code: "mi", name: "Maori", native: "Te Reo Māori" },
  { code: "sm", name: "Samoan", native: "Gagana Samoa" },
  { code: "qu", name: "Quechua", native: "Runa Simi" },
  { code: "ay", name: "Aymara", native: "Aymar aru" },
  { code: "gn", name: "Guarani", native: "Avañe'ẽ" },
  { code: "ht", name: "Haitian Creole", native: "Kreyòl Ayisyen" },
  { code: "la", name: "Latin", native: "Latina" },
  { code: "eo", name: "Esperanto", native: "Esperanto" },
  { code: "yi", name: "Yiddish", native: "ייִדיש", rtl: true },
  { code: "dv", name: "Dhivehi", native: "ދިވެހި", rtl: true },
  { code: "ug", name: "Uyghur", native: "ئۇيغۇرچە", rtl: true },
  { code: "bo", name: "Tibetan", native: "བོད་སྐད།" },
  { code: "dz", name: "Dzongkha", native: "རྫོང་ཁ" },
];

export function getLanguage(code: string): Language {
  return LANGUAGES.find((l) => l.code === code) ?? LANGUAGES[0];
}

export function isRtl(code: string) {
  return RTL_CODES.includes(code.split("-")[0]);
}
